# Generated by Django 5.1 on 2024-08-14 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchhistory',
            old_name='url',
            new_name='url_domain',
        ),
    ]
